### ISSUE TITLE
Problem populating datastore

### ISSUE THREAD

**Issue by wgAtTS** [dixieio/redux-json-api#15]
I'm having trouble getting redux-json-api to populate my data store. I've created an example project here: https://github.com/wgAtTS/react-redux-json-api

When I call dispatch() the action fires, and I can see JSON being returned from the server. However, the JSON never makes it into the redux store. Here's a screenshot of what I'm talking about:

<img width="445" alt="screen shot 2016-04-26 at 11 28 48" src="https://cloud.githubusercontent.com/assets/17067710/14816732/18bd1c0a-0ba2-11e6-99cd-9e2f637fb3fd.png">

api.tasks should not be null. You can ignore the additional "tasks" at the root level - I was using that for debugging (I'm new to React/Redux).

Can you provide any insight? Thanks!

**Comment by egeriis** [comment]
Hi @wgAtTS,

Looks like something fishy is going on. `isReading` should not become a `NaN`.

What about the payload that your API responds with, can you post that here?

**Comment by wgAtTS** [comment]
Sure! And thanks for the quick response. Here's a truncated version of what it's pulling down (sorry for formatting):

> {
  "data" : [ {
    "type" : "tasks",
    "id" : "1",
    "attributes" : {
      "creator" : 1,
      "lastUpdater" : 1,
      "name" : "Task 1",
      "description" : "Description for Task 1",
      "updatedOn" : 1456743266.662000100,
      "createdOn" : 1456743266.662000000
    },
    "relationships" : {
      "taskStatus" : {
        "links" : {
          "self" : "http://localhost:8080/api/tasks/1/relationships/taskStatus",
          "related" : "http://localhost:8080/api/tasks/1/taskStatus"
        },
        "data" : {
          "type" : "taskStatuses",
          "id" : "1"
        }
      },
      "function" : {
        "links" : {
          "self" : "http://localhost:8080/api/tasks/1/relationships/function",
          "related" : "http://localhost:8080/api/tasks/1/function"
        },
        "data" : {
          "type" : "functions",
          "id" : "1"
        }
      }
    },
    "links" : {
      "self" : "http://localhost:8080/api/tasks/1"
    }
  }, {
    "type" : "tasks",
    "id" : "2",
    "attributes" : {
      "creator" : 2,
      "lastUpdater" : 2,
      "name" : "Task 2",
      "description" : "Description for Task 2",
      "updatedOn" : 1456743266.662000100,
      "createdOn" : 1456743266.662000000
    },
    "relationships" : {
      "taskStatus" : {
        "links" : {
          "self" : "http://localhost:8080/api/tasks/2/relationships/taskStatus",
          "related" : "http://localhost:8080/api/tasks/2/taskStatus"
        },
        "data" : {
          "type" : "taskStatuses",
          "id" : "2"
        }
      },
      "function" : {
        "links" : {
          "self" : "http://localhost:8080/api/tasks/2/relationships/function",
          "related" : "http://localhost:8080/api/tasks/2/function"
        },
        "data" : {
          "type" : "functions",
          "id" : "2"
        }
      }
    },
    "links" : {
      "self" : "http://localhost:8080/api/tasks/2"
    }
  }],
  "included" : [ ]
}

**Comment by egeriis** [comment]
Fixed your formatting :) 

Me or one from our team will get back to you soon.

**Comment by Nopzen** [comment]
Hello @wgAtTS 

I had a quick look at your code, one thing i saw that might cause the issue is when you are firing the function:

```javascript
listTasks() {
  this.props.dispatch(readEndpoint('tasks'));
  this.props.actions.listTasks();
}
```

First you dispatch the `readEndpoint` witch is correct, witch then starts the api call, then you call the listsTasks, witch is fired right after the `readEndpoint`, here i see a possible issue, `readEndpoint` is async call and when you are calling the `listTasks(), simple tasks might not be there yet, can you try to move the list tasks in to the `onSuccess` call back:

```javascript
this.props.dispatch(readEndpoint('tasks', 
  onSuccess: () => {
    this.props.actions.listTasks(); }
  )
);
```

**Comment by wgAtTS** [comment]
I've simplified the code, but isReading is still showing isReading as NaN. I can see the GET request in Chrome's debugger returning JSON, but API is never populated.

    fetchTasks() {
        this.props.dispatch(readEndpoint('tasks'))
    };
    render() {
        return (
            <div>
                <button onClick={this.fetchTasks.bind(this)}>List Tasks</button>
            </div>
        )
    }

**Comment by Nopzen** [comment]
Hi @wgAtTS 

Im trying to troubleshoot a code a bit right now, im returning to you a bit later today, see if i found thing that could cause this `NaN` issue.

**Comment by wgAtTS** [comment]
Thank you!

**Comment by Nopzen** [comment]
@wgAtTS I your issue is in the way you configure your store, i can see you set a default store of:
```javascript
// Store object from Client.js line 11
// let store = configureStore({api:{tasks:[]}})
{
  api: {
    tasks: []
  }
}
```
This causes that you define the API object, and the the API object is not the one given from the Redux-json-api, therefore is it missing its `isReading` key, and when you run the fetch it cant find the previous key: value, and returns NaN.

Could you try to configure you store like this:
```javascript
let store = configureStore({});
```

Your Root reducer should set Api by it self on the state.

//Thanks in advance for trying :)

**Comment by wgAtTS** [comment]
Great! That did it. However, the tasks are still not being populated.

<img width="570" alt="screen shot 2016-04-28 at 15 07 49" src="https://cloud.githubusercontent.com/assets/17067710/14890640/0a683466-0d53-11e6-8763-a308ea0b35c6.png">


Am I correct in assuming the reducer should just be set up as:

    import { combineReducers } from 'redux'
    import { reducer as apiReducer } from 'redux-json-api'
    
    const rootReducer = combineReducers({
        api: apiReducer
    })

    export default rootReducer

Here is the full response that the client is receiving: https://gist.github.com/wgAtTS/d80bfad48cb464da265beff536433280#file-gistfile1-json

**Comment by Nopzen** [comment]
Great that it worked for you @wgAtTS

Let me look in to this, im gonna write some tests or set up a neutral test case (example repo) ill get back to you as soon as i know more, we have had issues with this before that its not populating it to the api.endpointName - This should not be an issue on your side as i see for now, let me get back to you later today if i have a solution.

**Comment by Nopzen** [comment]
@wgAtTS - Can you provide me your Request URL

**Comment by wgAtTS** [comment]
Sure! http://localhost:8080/api/tasks

I really appreciate the help :)

**Comment by egeriis** [comment]
Hey @wgAtTS, 

Did you see the issue with `Content-Type` header in #14?

I think that might be your issue, because it is not the correct `payload` that are passed through the `API_READ` action.

**Comment by egeriis** [comment]
I meant to reference issue #13

**Comment by wgAtTS** [comment]
Hmm. Here are the headers being sent back:

<img width="392" alt="screen shot 2016-04-28 at 21 01 26" src="https://cloud.githubusercontent.com/assets/17067710/14901390/8fee83b6-0d84-11e6-9e7e-b330f18ee95e.png">

Could it be that it's choking on the charset=UTF8?

Here's the OPTIONS request just before the GET hits, but everything looks okay to me:

<img width="567" alt="screen shot 2016-04-28 at 21 04 29" src="https://cloud.githubusercontent.com/assets/17067710/14901439/db9465c4-0d84-11e6-85b2-d3a1c62d2dab.png">

Btw - not sure if I mentioned this or not yet, but I'm trying to use your library with [Katharsis](http://katharsis.io/)

**Comment by egeriis** [comment]
Yup, that's what I was suspecting. The charset part of your Content-Type response header is messing up. It's fixed in #16, but yet to be released. 

We'll probably release tomorrow. Would that be fine for you?

**Comment by wgAtTS** [comment]
That would be fantastic :) Our app won't be in production for a while, but it will be a great help if we can start developing the React side of things.

Thanks a ton for the quick responses and patience. This is my first experience with React coming from Angular 1 ;)

**Comment by egeriis** [comment]
Fix have been pushed. Can you confirm that it's working?

**Comment by wgAtTS** [comment]
Works like a charm! Thanks so much!

I'll let you guys know if I run into anything else. As I get our app up, I would be happy to contribute via some kind of simple "starter" app project or some examples for React newbies like myself if you guys were interested.

**Comment by egeriis** [comment]
Great @wgAtTS! Thank you for your help regarding this issue.

Any contribution will be deeply appreciated.
